namespace: "microsoft"
name: "sql"
version: "1.1.1"
description: "Ansible collection for Microsoft SQL Server management"

authors:
  - "Sergei Petrosian <spetrosi@redhat.com>"

repository: "https://github.com/linux-system-roles/mssql"
# yamllint disable-line rule:line-length
documentation: "https://github.com/linux-system-roles/mssql/blob/master/README.md"
issues: "https://github.com/linux-system-roles/mssql/issues"

readme: "README.md"

license:
  - MIT

dependencies: {}

tags:
  - "mssql"
  - "microsoft"
  - "sql"
  - "database"
